#!/usr/bin/env python
from rosalind import *

# converts DNA sequence to RNA
if __name__ == "__main__":	
	f = open("data/rosalind_rna.txt",'r').readlines()
	fasta, seqs = fastaParse(f)
	seq = sequence(seqs[0])
	rna = seq.convertToRNA()
	print(rna)
