#!/usr/bin/env python
from rosalind import *
"""Solution to the k-Mer Composition problem in the Bioinformatics 
Stronghold section of Rosalind
location: http://rosalind.info/problems/kmer/
Problem: return the 4-mer composition of a squence 
"""
	
if __name__ == "__main__":
	f = open("data/rosalind_kmer.txt", 'r').readlines()
	fasta, sequence = fastaParse(f)
	nuc = ['A', 'C', 'G', 'T']

	kmers, kMers = kmerLex(nuc, sequence[0], 4)

	results = " ".join([str(kMers[k]) for k in kmers])
	print(results)
